// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {forward} from '../models';

export function Run(arg1:forward.Config):Promise<void>;

export function RunById(arg1:number):Promise<void>;

export function Status():Promise<Record<string, boolean>>;

export function Stop(arg1:string):Promise<void>;
