// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {forwardRule} from '../models';
import {bll} from '../models';

export function Add(arg1:forwardRule.ConfigForwardRuleUpdateData):Promise<bll.Result>;

export function CssIdCount(arg1:number):Promise<bll.Result>;

export function Delete(arg1:number):Promise<bll.Result>;

export function GetInfoById(arg1:number):Promise<bll.Result>;

export function List(arg1:number,arg2:number):Promise<bll.Result>;

export function Update(arg1:number,arg2:forwardRule.ConfigForwardRuleUpdateData):Promise<bll.Result>;
