// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Run(arg1) {
  return window['go']['bll']['forwardBll']['Run'](arg1);
}

export function RunById(arg1) {
  return window['go']['bll']['forwardBll']['RunById'](arg1);
}

export function Status() {
  return window['go']['bll']['forwardBll']['Status']();
}

export function Stop(arg1) {
  return window['go']['bll']['forwardBll']['Stop'](arg1);
}
