// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['bll']['ForwardRuleBll']['Add'](arg1);
}

export function CssIdCount(arg1) {
  return window['go']['bll']['ForwardRuleBll']['CssIdCount'](arg1);
}

export function Delete(arg1) {
  return window['go']['bll']['ForwardRuleBll']['Delete'](arg1);
}

export function GetInfoById(arg1) {
  return window['go']['bll']['ForwardRuleBll']['GetInfoById'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['bll']['ForwardRuleBll']['List'](arg1, arg2);
}

export function Update(arg1, arg2) {
  return window['go']['bll']['ForwardRuleBll']['Update'](arg1, arg2);
}
