// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sshServer} from '../models';
import {bll} from '../models';

export function Add(arg1:sshServer.ConfigSshServerC):Promise<bll.Result>;

export function Delete(arg1:number):Promise<bll.Result>;

export function GetInfoById(arg1:number):Promise<bll.Result>;

export function List(arg1:number,arg2:number):Promise<bll.Result>;

export function Update(arg1:number,arg2:sshServer.ConfigSshServerU):Promise<bll.Result>;
